# Generated by Django 3.2.23 on 2023-11-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_mode', models.BooleanField(default=False)),
                ('led_state', models.BooleanField(default=False)),
            ],
        ),
    ]
